name: Deploy from Notion to Pages

# on: [workflow_dispatch]
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
    
jobs:
  download_old-generate-push:
    runs-on: ubuntu-latest
    
    steps:
        # Download packages
      - name: Submodule Update
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          sudo apt-get update
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Download notion4ever
        uses: actions/checkout@v4
        with:
          repository: 'MerkulovDaniil/notion4ever'
          
      - name: Install packages
        run: pip install -r requirements.txt
        
      - name: Download current version of the site
        uses: actions/checkout@v4
        with:
          repository: 'hayleyqc/hayleyqc.github.io'
          ref: main
          path: _site
          
      - name: Run notion4ever
        run: python -m notion4ever
        env:
            SITE_URL: "https://hayleyqc.github.io"
            NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
            NOTION_PAGE_ID: ${{secrets.NOTION_PAGE_ID}}
      
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
